name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # O job 'build' está indentado com 2 espaços
  build:
    # 'runs-on' está indentado com 4 espaços
    runs-on: ubuntu-latest
    
    # 'steps' está no mesmo nível de 'runs-on'
    steps:
    # O primeiro passo ('- uses:') está indentado com 6 espaços
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # SUBIR OS SERVIÇOS COM DOCKER COMPOSE ---
    - name: Run services with Docker Compose
      run: docker compose up -d

    # RODAR OS TESTES DENTRO DO CONTAINER DA API ---
    - name: Run tests with pytest
      run: docker compose exec -T api python -m pytest
        
    - name: Run tests with pytest
      env:
        PYTHONPATH: .
      run: |
        python -m pytest  
