name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Roda o flake8 para verificar o estilo do código
        flake8 .
    
    # --- SUBIR OS SERVIÇOS EM SEGUNDO PLANO ---
    - name: Run services with Docker Compose
      run: docker compose up -d

    # --- RODAR OS TESTES DENTRO DO CONTAINER DA API ---
    - name: Run tests with pytest
      run: docker compose exec -T api python -m pytest
